# deploy - k2 deploy app bulrush-msk-stage-usw2-dp-sandbox -t msk-bulrush-test -b <build> --argocd --skip-checks
# delete - k2 delete app bulrush-msk-stage-usw2-dp-sandbox -t msk-bulrush-test
apiVersion: platform.segment.com/v1alpha1
kind: SegmentApplicationExperimental
cell: core
metadata:
  name: msk-bulrush-test
  namespace: msk-kafka-load
spec:
  targets:
  - name: msk-bulrush-test
    cluster: stage:us-west-2:dp-sandbox
    replicatedService:
      iamRoleName: msk-bulrush-test
      namespace: msk-kafka-load
      replicas: 1
      mainContainer:
        imageName: smsk-bulrush-test
        imageRegistry: 528451384384.dkr.ecr.us-west-2.amazonaws.com
        command:
        - "/bin/worker"
        - "-debug=false"
        - "-source.connect=kafka.dataplatform.segment.local:9092"
        - "-source.group-id=bulrush-test-cg-1"
        - "-source.topic=dp-test-onboarding"
        - "-sink.connect=kafka.dataplatform.segment.local:9092"
        - "-output-topic=dp-test-identified-messages"
        - "-address=:3000"
        resources:
          limits:
            cpu: 0.5
            memory: 256M
        ctlstore:
          disabled: true
        ports:
          - name: http
            containerPort: 3000
        healthCheckPath: "/internal/health"
