---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smsk-bulrush-test
  namespace: smsk-kafka-load
  labels:
    app: smsk-bulrush-test
    k2.segment.com/app: smsk-bulrush-test
    k2.segment.com/argocd: "true"
    k2.segment.com/build: bdaae35
    k2.segment.com/deploy: 2bd08911a9675d
    k2.segment.com/repo: smsk-bulrush-test
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
    version: bdaae35-2bd08911a9675d
  annotations:
    k2.segment.com/context: '{"appConfigMismatch":false,"appConfigSource":"file://.k2/bulrush-stage-usw2-dp-sandbox.yaml","appName":"smsk-bulrush-test","argoCDDeploy":true,"argoCDTestDeploy":false,"buildTag":"bdaae35","deployID":"2bd08911a9675d","deployTime":"2022-10-31T02:46:57.502027Z","fullDiffs":false,"host":"C02GK492MD6M","image":null,"k2Root":"/Users/ssingudasu/.kube/k2","k2Version":"0.10.0","repoBranch":"30oct2022-03","repoName":"smsk-bulrush-test","repoSHA":"bdaae357bc8b98acab0c9263e76fb257ca69317b","skipChecks":true,"skipChecksReason":"","targetCluster":"stage:us-west-2:dp-sandbox","targetName":"smsk-bulrush-test","user":"ssingudasu","workingDir":"/Users/ssingudasu/Desktop/twilio/projects/smsk-bulrush-test","shardDeployment":false}'
spec:
  strategy:
    {}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: smsk-bulrush-test
  template:
    metadata:
      labels:
        app: smsk-bulrush-test
        k2.segment.com/app: smsk-bulrush-test
        k2.segment.com/argocd: "true"
        k2.segment.com/build: bdaae35
        k2.segment.com/deploy: 2bd08911a9675d
        k2.segment.com/repo: smsk-bulrush-test
        k2.segment.com/skipped-checks: "true"
        segment.com/managed-by: k2
        version: bdaae35-2bd08911a9675d
      annotations:
        k2.segment.com/context: '{"appConfigMismatch":false,"appConfigSource":"file://.k2/bulrush-stage-usw2-dp-sandbox.yaml","appName":"smsk-bulrush-test","argoCDDeploy":true,"argoCDTestDeploy":false,"buildTag":"bdaae35","deployID":"2bd08911a9675d","deployTime":"2022-10-31T02:46:57.502027Z","fullDiffs":false,"host":"C02GK492MD6M","image":null,"k2Root":"/Users/ssingudasu/.kube/k2","k2Version":"0.10.0","repoBranch":"30oct2022-03","repoName":"smsk-bulrush-test","repoSHA":"bdaae357bc8b98acab0c9263e76fb257ca69317b","skipChecks":true,"skipChecksReason":"","targetCluster":"stage:us-west-2:dp-sandbox","targetName":"smsk-bulrush-test","user":"ssingudasu","workingDir":"/Users/ssingudasu/Desktop/twilio/projects/smsk-bulrush-test","shardDeployment":false}'
      name: smsk-bulrush-test
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
        - 169.254.20.10
        searches:
        - smsk-kafka-load.svc.cluster.local
        - svc.cluster.local
        - cluster.local
        - us-west-2.compute.internal
        options:
        - name: ndot
          value: '2'
      serviceAccountName: smsk-bulrush-test
      nodeSelector:
        segment.com/pool: main
      containers:
      - command:
        - /bin/worker
        - -debug=false
        - -source.connect=kafka-kafka.dp-sandbox.segment.local:9092
        - -source.group-id=bulrush-test-cg-1
        - -source.topic=test-1
        - -sink.connect=kafka-kafka.dp-sandbox.segment.local:9092
        - -output-topic=test-2
        - -address=:3000
        env:
        - name: GOMAXPROCS
          value: "1"
        - name: K8S_CONTAINER_NAME
          value: smsk-bulrush-test
        - name: K8S_DEPLOYMENT
          value: smsk-bulrush-test
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: K8S_POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SEGMENT_CELL
          value: core
        image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/smsk-bulrush-test:bdaae35
        livenessProbe:
          httpGet:
            path: /internal/health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 15
        name: smsk-bulrush-test
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /internal/health
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 15
        resources:
          limits:
            cpu: 250m
            memory: 256M
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: smsk-bulrush-test
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
      volumes:
        - hostPath:
            path: /var/spool/ctlstore
          name: ctlstore