---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: smsk-bulrush-test
  namespace: smsk-kafka-load
  labels:
    app: smsk-bulrush-test
    k2.segment.com/app: smsk-bulrush-test
    k2.segment.com/repo: smsk-bulrush-test
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smsk-bulrush-test
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75