---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: smsk-bulrush-test
    k2.segment.com/app: smsk-bulrush-test
    k2.segment.com/repo: smsk-bulrush-test
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
  name: smsk-bulrush-test
  namespace: smsk-kafka-load
spec:
  clusterIP: None
  ports:
  - port: 3000
    name: http
  selector:
    app: smsk-bulrush-test

