---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smsk-bulrush-test
  namespace: smsk-kafka-load
  labels:
    app: smsk-bulrush-test
    k2.segment.com/app: smsk-bulrush-test
    k2.segment.com/repo: smsk-bulrush-test
    k2.segment.com/skipped-checks: "true"
    segment.com/managed-by: k2
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::355207333203:role/dp-sandbox.usw2.eks.smsk-bulrush-test
